# SC Metrics Agent Configuration
# Copy this file to config.yaml and customize for your environment

# Collection settings
collection_interval: 30s
http_timeout: 30s

# Ingestor endpoint configuration
ingestor_endpoint: "https://api.cloud.strettch.dev/resource-manager/api/v1/metrics/ingest"

# Agent identification - VM ID will be automatically detected if not specified
vm_id: ""

# Additional labels to attach to all metrics
labels:
  environment: "production"
  region: "us-east-1"
  team: "platform"
  service: "web-frontend"

# Collectors configuration - specify which metrics to collect
collectors:
  # Process and system metrics
  processes: true
  cpu: true
  cpu_freq: true
  loadavg: true
  
  # Memory metrics  
  memory: true
  vmstat: true
  
  # Storage metrics
  disk: true
  diskstats: true
  filesystem: true
  
  # Network metrics
  network: true
  netdev: true
  netstat: true
  sockstat: true
  
  # System information
  uname: true
  time: true
  uptime: true
  entropy: true
  interrupts: true
  
  # Advanced metrics
  thermal: true
  pressure: true
  schedstat: true

# Logging configuration
log_level: "info"

# Security: Enable debug payload logging (SECURITY RISK - only enable for debugging)
# When enabled, shows sanitized payload previews in debug logs
# Default: false (secure - no sensitive data in logs)
enable_debug_payload_logs: false

# Retry settings
max_retries: 3
retry_interval: 5s