name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validation:
    name: Test, Lint & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true
    - name: Run tests
      run: make test

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.6
        working-directory: .

    - name: Build for Linux AMD64
      run: make GOOS=linux GOARCH=amd64 build

    - name: Verify binary
      run: |
        ls -la build/
        file build/sc-metrics-agent
        ./build/sc-metrics-agent -v

